countries/countries

- lib/data/countries.yaml
http://en.wikipedia.org/wiki/Lithuania_and_the_euro
> Lithuania adopted the Euro on 2015-01-01

- lib/data/subdivisions/SG.yaml
Updates Singapore subdivisions according to https://www.iso.org/obp/ui/#iso:code:3166:SG
> Update Singapore subdivisions to reflect ISO-3166-2:SG

- lib/data/subdivisions/CU.yaml
In partial response to #208 
Note: This PR only adds `CU-15` and `CU-16`, since that's the bare minimum of what should be done. It doesn't touch `CU-02` or `CU-03`, though something will need to be done with those too.
> Add Cuban Subdivisions - Artemisa and Mayabeque

- lib/data/countries.yaml
Russian is very common in Estonia.
> Add Russian as Estonian language

- lib/data/countries.yaml
- spec/country_spec.rb
The french translation had the spanish one, so I put it right together.
> Correct translation of Afghanistan for fr and es

- lib/countries/country.rb
- lib/data/countries.yaml
- spec/country_spec.rb
The primary language of Malaysia should be Malay, not English.
http://en.wikipedia.org/wiki/Malay_language
http://en.wikipedia.org/wiki/Languages_of_Malaysia
> Define primary language of Malaysia as Malay

- lib/data/countries.yaml
I recently had a user of my app from Barbados notice that the English version of Barbados was displayed as the French spelling. I'm just committing with the spelling they preferred and as it was listed in the official ISO document. Thanks. :)
> Corrected English spelling of Barbados

- lib/countries/country.rb
- lib/data/countries.yaml
- spec/country_spec.rb
These categories are commonly used in global commerce, but aren't trivial to deduce from existing regional information, specifically in the Middle East, where countries like Israel and Jordan are in the region "Asia / Western Asia" but in the EMEA group.
For reference, the list of countries and their regions: https://support.google.com/richmedia/answer/1381064?hl=en
> Added World Regions (APAC, EMEA, AMER) to countries.

- lib/data/subdivisions/CU.yaml
`CU-02`: La Habana ==> Provincia de La Habana
`CU-03`: Ciudad de La Habana ==> La Habana
Note: `CU-02` no longer exists and is being renamed because of the potential conflict with CU-03's name
> Rename CU-02 to 'Provincia de la Habana' and CU-03 to 'La Habana'

- lib/countries/country.rb
- lib/data/countries.yaml
- spec/country_spec.rb
I've added the VAT rates for all countries in the European Union[1].
Most important rate is usually the standard rate, reduced/parking rates are merely informational.
The reason why I'm adding these is that, from 1 January 2015, EU businesses will have to use the VAT rate of the (EU) country of residence of the private customer, instead of the country where the business is located.
[1] Source: http://ec.europa.eu/taxation_customs/resources/documents/taxation/vat/how_vat_works/rates/vat_rates_en.pdf
> Added VAT rates to EU countries

- README.markdown
- lib/countries/country.rb
- lib/data/countries.yaml
- spec/country_spec.rb
GEC/FIPS-10 has been deprecated, but I needed it so the world might as well have it.
Sorry about the formatting of the data file, there was no way I was adding these codes by hand and some of the formatting got changed.  I wrote a nasty little spec to recursively check that I hadn't changed any country's attributes (not here) and it's all fine.
> Add GEC (FIPS-10) code

- lib/data/countries.yaml
We use the countries gem to look up information for addresses we get from Stripe, which sometimes has funny punctuation (or lack of) or misspellings in the country names; this PR adds all the country names that Stripe uses as alternate names in the appropriate entries.
> Add country names used by Stripe as alternate names

- lib/countries/country.rb
- spec/country_spec.rb
Implement ruby's [conversion idiom](http://www.ruby-doc.org/core-2.1.3/Kernel.html) for ISO3166::Country class, so:
```ruby 
country = ISO3166::Country.search('US')
ISO3166::Country(country) #=> #<Country:0x007f9c61e0ea20 @data={....}>
ISO3166::Country('us') #=> #<Country:0x007f9c61e0ea20 @data={....}>
ISO3166::Country(42) #=> raises TypeError, "can't convert Fixnum into ISO3166::Country"
```
> Add conversion method ISO3166::Country()

- lib/data/countries/ES.yaml
According to this document the region for address labels in Spain has to
be printed in a separate line:
http://www.upu.int/fileadmin/documentsFiles/activities/addressingUnit/espEn.pdf
> Fix address format for Spain

- README.markdown
I removed `The gem also adds a country_select helper` since it's no longer true.
I also removed the section titled 'Country Select Helper. I'm not sure if this is correct. Maybe we still want to mention it, just in a different way?
> Remove bit about country_select in README

- lib/countries/mongoid.rb
- spec/mongoid_spec.rb
Current mongoid Country field type behavior makes invalid country values raise a `BadMongoidTypeError` exception on assignation.
This is not the behavior of other Mongoid types ; actually `BadMongoidTypeError` error only exists in this country gem...
When you assign invalid values on base Mongoid types, like `Integer`, no exception is raised. The value is just set to the closest approximation: an integer field is just set to zero when assigning a string.
This PR brings this standard behavior to the Country field: when an invalid value is assigned, the field is set to `nil`, with no exception.
If you want to ensure the validity of the field content, just validate the field presence: if it's not empty, then it's a valid country !
> Fix mongoid field behavior

- Gemfile
- Rakefile
- countries.gemspec
- lib/countries.rb
- lib/countries/country.rb
- lib/countries/mongoid.rb
- lib/iso3166.rb
- spec/country_spec.rb
- spec/mongoid_spec.rb
This conversion is done by Transpec 3.0.7 with the following command:
transpec
* 114 conversions
from: obj.should
to: expect(obj).to
* 42 conversions
from: == expected
to: eq(expected)
* 10 conversions
from: collection.should have(n).items
to: expect(collection.size).to eq(n)
* 3 conversions
from: be_true
to: be_truthy
* 3 conversions
from: it { should ... }
to: it { is_expected.to ... }
* 3 conversions
from: obj.should have(n).keys
to: expect(obj.keys.size).to eq(n)
* 3 conversions
from: obj.should_not
to: expect(obj).not_to
* 2 conversions
from: be_false
to: be_falsey
* 2 conversions
from: lambda { }.should
to: expect { }.to
* 1 conversion
from: > expected
to: be > expected
* 1 conversion
from: obj.should_receive(:message)
to: expect(obj).to receive(:message)
For more details: …
> Convert specs to RSpec 2.99.2 syntax with Transpec

- lib/countries/country.rb
- spec/country_spec.rb
The newly added translation method in ISO3166::Country should return nil
rather than throwing an I18nData::NoTranslationAvailable exception if a 
translation is not found.
> Return nil if translation is not found

- lib/data/countries/AU.yaml
- lib/data/countries/BR.yaml
- lib/data/countries/CA.yaml
- lib/data/countries/CN.yaml
- lib/data/countries/HK.yaml
- lib/data/countries/ID.yaml
- lib/data/countries/IE.yaml
- lib/data/countries/IT.yaml
- lib/data/countries/JP.yaml
- lib/data/countries/KR.yaml
- lib/data/countries/MX.yaml
- lib/data/countries/PH.yaml
- lib/data/countries/PT.yaml
- lib/data/countries/TW.yaml
- lib/data/countries/UA.yaml
- lib/data/countries/US.yaml
The {{region}} placeholder was used ambiguously in address_format.
According to the discussion at http://github.com/hexorx/countries/pull/221
we agreed on using different placeholders, {{region}} and {{region_short}}, 
depending on whether the full region name (like 'Bayern' for Germany) or 
the abbrevation (like 'NY' in US address format) should be used.
This commit replaces any occurence of {{region}} by {{region_short}}
where {{region}} was not used on a separate line in the YAML files in
the /lib/data/countries directory.
> Use {{region_short}} in address_format

- README.markdown
There was a small typo, also it wasn’t the same as specified a line before.
> Update german translation in the examples (README.markdown)

- Rakefile
- lib/countries/country.rb
These commits are removing some of the warnings that appears when running a dependent gem/app in verbose mode (`ruby -w`).
Some of those warnings are code-smells, so that's why I'm trying to get rid of them.
Please tell me if you wanna squash those. I didn't as they're basically isolated and independent from one another.
Thanks for this gem!
> Enabling Ruby warnings

- lib/data/countries/KR.yaml
"South Korea" is commonly used in popular media to refer to the Republic of Korea (KR). Can we add this as an alias?
http://en.wikipedia.org/wiki/South_Korea
> Add "South Korea" as alias name for KR

- README.markdown
`Country#subdivisions` and `Country#states` returns an array of hashes with string keys, not symbols.
> Fix Subdivisions & States in README

- Rakefile
- lib/data/subdivisions/NA.yaml
- lib/data/subdivisions/US.yaml
When Google's geocoder is passed "New York, United States", it actually returns the geocoding information for New York City, and not the actual state. So the previously stored details were for the extent of the city, rather than the state. This fixes the initial geocoding logic by making a special case for New York to geocode "New York State". The stored YAML details have been updated with the new results for the state.
I've seen Google's geocoder change how it geocodes the string "New York" over the years, but appending "State" to the end has been a reliable way to force it to geocode the state (at least in my experience for the past couple years). So I think this approach should be safe in case anyone want to do a full re-geocoding sometime in the future.
When re-running the geocoding, …
> Fix New York, Washington, Oklahoma state's latitude/longitude information

- lib/data/subdivisions/UY.yaml
Issue : 
There were Bad / Invalid data which were found in the state data for Uruguay. This resulted in null data when the countries data was loaded.
Fix:
Removed the bad data that was present in Uruguay i.e removed ~X1,~X2 and ~X3.
> Bad state data present in Uruguay has been removed

- lib/data/countries/NO.yaml
Actually, the languages used in Norway are:
- 'nb' Norwegian Bokmål
- 'nn' Norwegian Nynorsk
> Update languages in NO.yml

- lib/data/countries/MO.yaml
Macau is used by Stripe
https://en.wikipedia.org/wiki/Macau
> Add alternate spelling of Macao/Macau

- lib/data/countries/MO.yaml
Macao doesn't have a currency at the moment but it should be MOP. 
http://www.currency-iso.org/en/home/tables/table-a1.html
https://en.wikipedia.org/wiki/ISO_4217
http://www.xe.com/iso4217.php
> Add MOP as the currency for Macao

- lib/data/countries/AQ.yaml
- lib/data/countries/AX.yaml
- lib/data/countries/CD.yaml
- lib/data/countries/GQ.yaml
- lib/data/countries/GS.yaml
- lib/data/countries/MG.yaml
- lib/data/countries/NU.yaml
- lib/data/countries/PS.yaml
- lib/data/countries/VU.yaml
A few countries are missing currency information. The following snippet lists their currencies as listed on Wikipedia.
Country | Currency
------------ | -------------
Antarctica | None<sup>1</sup>, but United States Dollar is common (USD)
Åland Islands | Euro (EUR)
Congo | Central African CFA franc (XAF)
Equatorial Guinea | Central African CFA franc (XAF) 
South Georgia and the South Sandwich Islands | Pound sterling (GBP)
Madagascar | Malagasy ariary (MGA)
Niue | New Zealand dollar (NZD)
Palestine, State of | New Israeli Shekel (ILS), Egyptian Pound (EGP), Jordinian Dinar (JOD)<sup>2</sup> 
Vanuatu | Vanuatu vatu (VUV)
<sup>1</sup>No official currency, although they do have a novelty Antarctic Dollar that can be bought in the United States, it isn't legal tender anywhere. Each base seems …
> Add missing currency information

- lib/data/countries/IT.yaml
Mobile telephones in Italy can be from 9 to 11 digits long.
https://en.wikipedia.org/wiki/Telephone_numbers_in_Italy#Number_format
> Correct telephone number lengths in Italy

- README.markdown
- lib/countries/country.rb
- spec/country_spec.rb
Pull request for #297
Usage example:
```ruby
c = Country[:BE]
c.local_names #=> ["België", "Belgique", "Belgien"]
c.local_name #=> "België"
```
> Add local_names and local_name methods to Country instances

- lib/countries/data/subdivisions/NZ.yaml
Hawke's Bay had an extra unwanted _s_, and the Chatham Islands had an unnecessary space.
> Fix NZ typo's.

- lib/countries/data/subdivisions/PT.yaml
Açores and Madeira are the names used for these subdivisions: https://pt.wikipedia.org/wiki/ISO_3166-2:PT
> Corrected Naming for Portugal subdivisions

- lib/countries/country.rb
Added ability to pass locale as symbol to avoid behavior like that:
```
2.1.5 :017 > Country["AT"].translation :de
=> nil 
2.1.5 :018 > Country["AT"].translation "de"
=> "Österreich"
```
> Force converting passed locale to string

- lib/countries/data/countries/CG.yaml
Sources:
http://www.oanda.com/help/currency-iso-code-country
https://en.wikipedia.org/wiki/CFA_franc#Central_African
https://en.wikipedia.org/wiki/Central_African_CFA_franc
> Added XAF as currency code for Congo

- lib/countries/data/countries/BV.yaml
Sources:
https://en.wikipedia.org/wiki/Bouvet_Island
http://en.advisto.com/country-phone-codes.htm
Fixes one example in #315
> Added 47 as calling code for Bouvet Island, Norwegian territory

- lib/countries/data/countries/RO.yaml
See: http://www.vatlive.com/european-news/romania-confirms-vat-rate-cut-to-20-2016/
> Romanian Standard VAT rate is 20% as of 2016-01-01

- lib/countries/data/subdivisions/US.yaml
The US state Florida currently has incorrect min/max latitude and longitudes (-90, -180 and 90,180). I cleared these and re-ran the `rake fetch_subdivisions` task to fetch the latest boundaries from the geocoder.
> Fix the min/max lat/lon of Florida

- lib/countries/data/countries/EE.yaml
RU is not an official language of Estonia.
> Update EE.yaml remove ru from languages

- lib/countries/data/subdivisions/PH.yaml
There were 2 subdivisions missing which I have added - DIN and DVO
There is also a set of regions for PH https://en.wikipedia.org/wiki/ISO_3166-2:PH
All subdivisions are within a region except for the Region of `00` which has no subdivisions. I've added `00` and could add the other subdivisions (similar to what appears to exist for the UK). 
Is this PR good or should I add the additional PH regions?
> Update PH Subdivisions

- lib/countries/data/subdivisions/US.yaml
While trying to iterate over each US state, I found that while most states have a single value for the `names` key, California had multiple values. The other states included only the English version of the name, while California included some translations;
```
AZ
{"name"=>"Arizona", "names"=>"Arizona"}
CA
{"name"=>"California", "names"=>["Californie", "Kalifornien"]}
CO
{"name"=>"Colorado", "names"=>"Colorado"}
CT
{"name"=>"Connecticut", "names"=>"Connecticut"}
```
This causes some unexpected behavior when iterating over each state's information. 
If the plan is to add multiple translations for all states, then this PR isn't necessary. However, if there are no plans to do so, I think it would be helpful to keep these consistent.
> Make California's 'names' value match other states' style

- lib/countries/data/subdivisions/RU.yaml
- spec/subdivision_spec.rb
- replaced in lib/countries/data/subdivisions/RU.yaml rows like 
`translations: Республика Адыгея`
to
`translations:`
&nbsp;&nbsp;`ru: Республика Адыгея`
- added spec, which checks if ISO3166::Subdivision.translations is either Hash or nil
> fix: add hash keys for translations of russian regions

- lib/countries/data/subdivisions/AM.yaml
The previous coords were a little bit off pointing to some place in Spain instead of Armenia.
> Update Lorri subdivision (AM-LO) coords

- countries.gemspec
Listing the license in the gemspec can be useful for other tools that read gem dependencies.
More info at [Gemspec#license=](http://guides.rubygems.org/specification-reference/#license=)
> adding MIT license to gemspec

- lib/countries/data/countries/ZW.yaml
The successor is difficult, but the Zimbabwean Dollar was demonetised in 2015 and replaced with a basket of currencies. The government uses the USD in official transactions, however.
> Change Zimbabwe currency code to USD

- countries.gemspec
This gem (countries) depends on money ~>6.0 and requires `sixarm_ruby_unaccent` in countries.rb. The problem is, `sixarm_ruby_unaccent` is a dependency of money v6.7 and up. One of our gems depends on an earlier version of money, so countries >= 2.0 caused our builds to error.
This PR updates countries to depend on money 6.7 and above.
> Restrict money version to ~> 6.7

- countries.gemspec
`countries` requires `sixarm_ruby_unaccent` (as included in `lib/countries.rb`), however it's not listed as a dependency. This causes breakages unless the gem already happens to be installed or it's installed manually.
> Add sixarm_ruby_unaccent to gemspec dependencies

- lib/countries/data.rb
- spec/perf_spec.rb
2.0.5 Benchmark
```
Rehearsal --------------------------------------------------
find_by_alpha2   2.520000   0.040000   2.560000 (  2.574010)
new              0.310000   0.010000   0.320000 (  0.325458)
----------------------------------------- total: 2.880000sec
user     system      total        real
find_by_alpha2   2.500000   0.030000   2.530000 (  2.546312)
new              0.300000   0.000000   0.300000 (  0.297833)
```
HEAD Benchmark
```
Rehearsal --------------------------------------------------
find_by_alpha2   0.450000   0.000000   0.450000 (  0.446878)
new              0.030000   0.000000   0.030000 (  0.027353)
----------------------------------------- total: 0.480000sec
user     system      total        real
find_by_alpha2   0.470000   0.000000   0.470000 (  0.486354)
new …
```
> Unnecessary call to uniq causing perf regression.

- lib/countries/data/countries/RO.yaml
Down from 20%.
http://www.vatlive.com/vat-news/romania-cuts-vat-to-19-2017/
> Romanian standard VAT rate 19% since 2017-01-01

- lib/countries/data/subdivisions/TM.yaml
The TM-X~ subdivision is not listed in the ISO-3166-2 specification at
https://www.iso.org/obp/ui/#iso:code:3166:TM
Wikipedia article
https://en.wikipedia.org/wiki/Template:ISO_3166_name_TM-X~
indicates TM-X~ returns Turkmenistan instead of a subdivision within
Turkmenistan.
Also, the TM-X~ subdivision does not have a name.
So this entry should not exist.
> Remove empty Turkmenistan subdivision TM-X~

- lib/countries/data/subdivisions/PH.yaml
The PH-MNL subdivision is not listed in the ISO-3166-2 specification at
https://www.iso.org/obp/ui/#iso:code:3166:PH
Wikipedia article
https://en.wikipedia.org/wiki/Template:ISO_3166_name_PH-MNL
indicates PH-MNL returns Philippines instead of a subdivision within
Philippines.
Also, the PH-MNL subdivision in Philippines does not have a name.
So this entry should not exist.
> Remove empty Philippines subdivision PH-MNL

- .travis.yml
- countries.gemspec
- lib/countries/country/emoji.rb
https://rubygems.org/gems/countries/versions/2.0.8 seems to suggest that the latest version of the gems works with any Ruby, however, when trying to install on anything lower than 2.0.0 *, the UTF-8 characters in emojis.rb caused a `invalid multibyte char (US-ASCII)` as older rubies don't autodetect the encoding.
This is easily fixed by adding a magic comment to the file in question, and the tests now happily pass on 1.9.3. I've also had to add a slight tweak the the gemfile, as the VERSION constant is a frozen string, but this doesn't affect the functionality of the gem.
For good measure, I've added `1.9.3` to the Travis setup just to make doubly sure everything passes ongoing.
\* I know 1.9.x is EOL, but we're on legacy infrastructure at the moment, so need to struggle along, at least …
> Support older rubies

- lib/countries/data/countries/HK.yaml
The demonym of Hong Kong is Hongkonger or Hong Kongnese https://en.wikipedia.org/wiki/Hong_Kong
https://en.wikipedia.org/wiki/Hong_Kong_people
Some users from Hong Kong reported this today:
> "I had a chuckle when I had to choose my nationality and Hong Kongese wasn't in the list, I chose North Korean as I found it funny how that one was there but a semi-sovereign city with 7 million people isn't. Most Hong Kong people (including myself) do no associate ourselves as being Chinese despite ethnically being one :)" - User
> Changed the nationality of Hong Kong from Chinese to Hong Kongnese

- lib/countries/country/class_methods.rb
- spec/country_spec.rb
Currently you are left with the following if you 
```
$ gem install countries 
$ irb
irb(main):001:0> require 'countries/global'
=> true
irb(main):003:0> ISO3166::Country.all_names_with_codes
NoMethodError: undefined method 'html_safe' for "Andorra":String
```
The proposed patch writes out the dependency for active_support by removing the use of html_safe with backwards compatibility, although I am unsure it was needed in the first place.
Hope it can be considered as not everyone use active_support all the time. 
Regards
Subfusc
> Write out dependence of active_support in all_names_with_codes

- lib/countries/data/countries/GB.yaml
'Великобритания' is russian for 'Great Britain'
Hello, we are using your gem to match russian country names to alpha2 codes like this:
```ruby
def country_alpha2(name)
(ISO3166::Country.find_by_translated_names(name) || ISO3166::Country.find_by_names(name))&.first
end
```
`country_alpha2('Великобритания')` returns nil since there can only be one translated name per locale in `i18n_data` gem and it is 'Соединенное королевство' which means 'United Kingdom'.
If I add this unofficial name which is widely used in Russia then the match will work.
I could not find if such contributions are being adopted to your data.
> Add russian unofficial name to GB

- lib/countries/country.rb
- spec/data_spec.rb
At present subdivisions are always loaded from files (even if the country is custom registered). This fix enables passing subdivison data to `ISO3166::Data.register`
> allow to register subdivisions

- lib/countries/data.rb
- spec/data_spec.rb
e.g. in config/initializers/countries.rb:
`ISO3166::Data.cache_dir = [Rails.root, "config"]`
> Allow to override cache dir

- lib/countries/subdivision.rb
I know the subdivision files don't have codes, but it can be handy when using custom data or `ISO3166::Data.register`
> add code attribute to Subdivision

- lib/countries/data/subdivisions/MX.yaml
Reference: https://www.theguardian.com/world/2016/jan/29/mexico-city-name-change-federal-district-df
> Updates MX.yaml to reflect Mexico City's official name change

- lib/countries/data/subdivisions/AM.yaml
- lib/countries/data/subdivisions/KH.yaml
- lib/countries/data/subdivisions/LY.yaml
- lib/countries/data/subdivisions/SA.yaml
- lib/countries/data/subdivisions/SD.yaml
- lib/countries/data/subdivisions/SY.yaml
- lib/countries/data/subdivisions/YE.yaml
- lib/countries/tasks/geocoding.rake
Fixes #436 This is a by hand correction to prevent noise of the CLDR import.   It includes handful of updates to incorrect data sets and adds some Arabic translations.
Source Wikipedia.
> Fix corrupted Subdivisions

- lib/countries/data/countries/TW.yaml
TW(Taiwan) national prefix number is 0.
It is also 0 in Google's libphonenumber library.
https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml#L23907
line: 23907
```
<territory id="TW" countryCode="886" internationalPrefix="0(?:0[25679]|19)" nationalPrefix="0"
preferredExtnPrefix="#" nationalPrefixFormattingRule="$NP$FG"
mobileNumberPortableRegion="true">
```
> fix TW national_prefix

- lib/countries/country/class_methods.rb
- spec/country_spec.rb
Using ISO3166::Country.find_country_by_name('Korea, Republic of')
returns nil, since Korea is stored as "Korea (Republic of)".
This change will normalize all the terms that are used to search and
those in the Data.cache.
> Fix search to work for countries with comma in their name

- lib/countries/country.rb
- spec/country_spec.rb
> Add subdivision names with codes

- lib/countries/data/countries/CH.yaml
Updated Switzerland VAT rates, see https://www.ch.ch/en/vat-rates-switzerland/
> Updated Switzerland VAT rates

- lib/countries/country.rb
- lib/countries/country/class_methods.rb
Currently the subdivision YAML files are being loaded for every new `Country` instance. This PR memoizes the loaded YAML file on a class instance variable.
Also replaced the `inject` -> `merge` pattern with a more performant version.
Performance changes:
From:
```ruby
pry(main)> Benchmark.realtime { 10000.times { Country['US'].subdivisions } }
=> 17.20118099998217
```
To:
```ruby
pry(main)> Benchmark.realtime { 10000.times { Country['US'].subdivisions } }
=> 0.6878289999440312
```
> Memoize subdivision YAML loading

- lib/countries/data/countries/GR.yaml
Standard from 23% to 24%
Reduced from [6.5, 13] to [6, 13]
Sources:
http://www.vatlive.com/vat-rates/european-vat-rates/eu-vat-rates/
http://www.vatlive.com/european-news/greece-new-vat-rises-in-creditor-talks/
> Corrected VAT rates of Greece

- README.markdown
The wrong flag was in there! :)
```
irb(main):006:0> c = ISO3166::Country.new('MY').emoji_flag
=> "🇲🇾"
```
> Fixed incorrect flag emoji in Readme example

- lib/countries/data/countries/NP.yaml
urdf is not a valid language code, but urd is the valid code for Urdu
> Fixing language code for Urdu to ISO 639-2

- README.markdown
Sort of unrelated but I was also wondering if the code example makes sense with `alpha2: 'LOL'` - because of the alpha2 country code being 3 letters and not 2.
> Consistently use single-quotes in code block

- lib/countries/data/countries/CZ.yaml
Recently, Czech Republic accepted to add a shorter variation of the country name, which is Czechia, in order to provide better recognition, similar to 'France' (The French Republic) and Turkey (Republic of Turkey). However, they will retain the full name (Czech Republic), and Czechia will become the official short geographic name. This PR adds 'Czechia' to the name catalog.
- https://www.bbc.com/news/world-europe-36048186
- https://www.daytranslations.com/blog/2018/03/czechia-why-did-they-change-their-name-10935/
This PR Closes #560
> Add Czechia as unofficial name for Czech Republic

- README.markdown
iso-codes now uses debian's gitlab instance called salsa. see https://wiki.debian.org/Salsa
> Fixed links to debian package iso-codes

- README.markdown
"its" is the correct form of the possessive. Apologies if this is too pedantic a pull request!
> Fix "it's"-related typos

- countries.gemspec
bin/console shouldn't be packaged as an executable
> remove bin/console from gemspec

- lib/countries/data/countries/MK.yaml
Macedonia will soon officially be known as the Republic of North Macedonia, per https://www.bbc.com/news/world-europe-47002865
North Macedonia is an appropriate alternate name effective immediately
> Add North Macedonia as alternate name

- lib/countries/country/class_methods.rb
- spec/country_spec.rb
Recently we started using this gem in our project and found that our tests had slowed down by half. They went from ~4 mins to ~8 mins. One of our team traced the slowdown to the countries gem and so we started doing some investigation.
Object creations:
----------
What it seems to come down to is the fact that when `parse_value` is called, it creates many String objects each time it is called. When searching through all the countries, this method gets called _a lot_ inside of a loop. I did a check for object allocations from calling `find_by` once and it generated somewhere between 40,000 and 50,000 new String objects. 
Overall Performance:
-----------
We also created a simple test to loop 1000 times and call `find_by` and we found that it was taking more than 10 seconds to complete. In …
> Add caching to the parsing of values during search

- lib/countries/data/countries/MK.yaml
The name of `Macedonia` was changed to `North Macedonia` on the 13th of March 2019 -> https://www.iso.org/obp/ui/#iso:code:3166:MK
> Change the name of Macedonia to North Macedonia

- lib/countries/data/countries/NL.yaml
I would even go so far as to say that in common usage "The Netherlands" is more common than "Netherlands"
> Add "The Netherlands" as an unofficial name of NL

- lib/countries/data/countries/GB.yaml
UK has left the EU and EEA. Updating the details.
https://www.gov.uk/eu-eea
> Update UK EU and EEA status

- lib/countries/data/subdivisions/IE.yaml
This change updates the formatting of the subdivision yml file for Ireland (IE). The formatting was standardized using `rake update_yaml_structure`. 
Additionally, the information for the subdivisions `C` and `CO` have been updated to reflect information from [Wikipedia](https://en.wikipedia.org/wiki/ISO_3166-2:IE) for Connacht and (County) Cork respectfully.
Fixes: https://github.com/hexorx/countries/issues/594
> Update Ireland Subdivision Formatting and Connacht and (County) Cork Data

- lib/countries/data/subdivisions/CL.yaml
Closes: #592
Chile converted Ñuble province to a region. I wasn't sure what are the translations for it in these languages, feel free to comment / add:
> Add Ñuble region

- lib/countries/data/subdivisions/FO.yaml
- lib/countries/data/subdivisions/SD.yaml
- spec/subdivision_spec.rb
This bug was caused by YAML being "helpful" and parsing "NO" as false.
YAML will also parse "YES", "No", "no", "on", "off" and many other
variations as boolean.
https://makandracards.com/makandra/24809-yaml-keys-like-yes-or-no-evaluate-to-true-and-false
> Fix state codes from being returned as false

- lib/countries/data/subdivisions/GB.yaml
https://en.wikipedia.org/wiki/East_Riding_of_Yorkshire
> [GB] Add unofficial names for ERY

- lib/countries/data.rb
I wouldn't call this PR ready until someone can confirm that this is a real fix.
I attempted to use the small reproduction of the thread safety issue but could not get it to fail locally.
In general, though, this puts a semaphore around access to the `ISO3166::Data.config`, ensuring that threads aren't entering this method during another thread's execution of this.
> Potential solution for thread safety

- lib/countries/data/countries/VN.yaml
Based on the source provided in #652, I added the format as:
```
address_format: |-
{{recipient}}
{{street}}
{{city}}
{{region}}
{{country}}
```
> Add address_format for Vietnam, fixes #652

- lib/countries/data/countries/GB.yaml
I would also propose adding "Great Britain" and removing "Great Britain (UK)" as that is not, in my view an unofficial name but rather the conjunction of two unofficial names, which the parenthesis serving as an "AKA." But the biggest issue is that "UK" should be a name and that's what this change does.
> UK is an unofficial name for Great Britain

- README.markdown
I came across this `find_all_by` method when looking at the gem's source code. It might be useful for other people to have an example on readme.
> add find_all_by example to readme

- lib/countries/data.rb
- spec/thread_safety_spec.rb
This PR fixes issue #499 by use of a Mutex in the `Data` class
We at @factorialco use (multi-thread but not multi-worker) Puma in production and have been hit by it just recently
I've added a failing test that checks that a race condition happens when the mutex isn't present and doesn't when it is present. I've run this 1000 times using a script and haven't got a single failure.
The test is fairly rough and it's not unitary by any means, but I think it's clearly an improvement
> Make cache thread safe

- lib/countries/data/translation_corrections.yaml
Currently translated as "Ryska federationen" which is as though the English translation had been "Russian Federation" – not what you'd normally call it.
Since the GB = "Storbritannien" correction was made without a corresponding correction in https://salsa.debian.org/iso-codes-team/iso-codes/-/blob/main/iso_3166-1/sv.po (or https://hosted.weblate.org/translate/iso-codes/iso-3166-1/sv) I assumed this would be fine also. Though I may try to raise an issue there too.
EDIT: Poked around more and realised the English translation *is* "Russian Federation" :) Perhaps it would be a good idea to change that one to "Russia"? I'll leave that for a separate PR, though.
> Swedish translation correction: RU = "Ryssland"

- README.markdown
Changes:
- Fix typo for currency support line
- Correct Markdown syntax inconsistency and errors
> Fix typo and lint in README.markdown

- lib/countries/data/countries/KP.yaml
It is pretty common to call `Democratic People's Republic of Korea` `North Korea` yet it is not present in the list of unofficial name and if we try to find country data for `North Korea` we get `nil` instead which leads to unexpected errors. Adding North Korea to the list of unofficial names improves accuracy of the matches and also fixes these issues.
> Adds North Korea to list of unofficial names of KP

- lib/countries/data/countries/CH.yaml
> The EEA includes EU countries and also Iceland, Liechtenstein and Norway. It allows them to be part of the EU’s single market.
> 
> **Switzerland is not an EU or EEA member** but is part of the single market. This means Swiss nationals have the same rights to live and work in the UK as other EEA nationals.
Source: https://www.gov.uk/eu-eea
> CH is not part of the EEA

- lib/countries/data/subdivisions/VN.yaml
Here are the changes: 
- Update some missing data for `vi` locale with translated data from `en` locale
- Update data from [ISO_3166-2:VN](https://vi.wikipedia.org/wiki/ISO_3166-2:VN)
- Sort data by order: municipality (HCMC, Ha Noi, ...) -> alphabetical order of provinces (An Giang, Bà Rịa - Vũng Tàu, Bắc Giang, ...) that yields exact data for practical select
```ruby
ISO3166::Country.new('VN').subdivisions.each_pair.map{|_, x| x[:translations]['vi'] }
```
- Resolve duplicates  eg. `Ho Chi Minh, thanh pho [Sai Gon]` -> `Ho Chi Minh City` 
- `Ha Tay` is merged to `Ha Noi`
> Update Vietnam subdivisions with current ISO_3166-2:VN

- lib/countries/country/class_methods.rb
- spec/country_spec.rb
This is code by @wmnnd from issue #550.
When adding a custom country with `ISO3166::Data.register`, it does not end up in the translation list. This PR merges those custom registered countries into the translations.
> Add custom countries to translation lists

- lib/countries/data.rb
- spec/data_spec.rb
This addresses the issue mentioned in https://github.com/countries/countries/pull/397#issuecomment-846543094
(cc @kg-currenxie)
> Fix ISO3166::Data.register loading of nested hashes, eg: geo data.

- lib/countries/country.rb
- lib/countries/data/countries/AT.yaml
- lib/countries/data/countries/BE.yaml
- lib/countries/data/countries/BG.yaml
- lib/countries/data/countries/CH.yaml
- lib/countries/data/countries/CY.yaml
- lib/countries/data/countries/CZ.yaml
- lib/countries/data/countries/DE.yaml
- lib/countries/data/countries/DK.yaml
- lib/countries/data/countries/EE.yaml
- lib/countries/data/countries/ES.yaml
- lib/countries/data/countries/FI.yaml
- lib/countries/data/countries/FR.yaml
- lib/countries/data/countries/GR.yaml
- lib/countries/data/countries/HR.yaml
- lib/countries/data/countries/HU.yaml
- lib/countries/data/countries/IS.yaml
- lib/countries/data/countries/IT.yaml
- lib/countries/data/countries/LT.yaml
- lib/countries/data/countries/LV.yaml
- lib/countries/data/countries/MT.yaml
- lib/countries/data/countries/NL.yaml
- lib/countries/data/countries/NO.yaml
- lib/countries/data/countries/PL.yaml
- lib/countries/data/countries/PT.yaml
- lib/countries/data/countries/RO.yaml
- lib/countries/data/countries/SE.yaml
- lib/countries/data/countries/SI.yaml
- lib/countries/data/countries/SK.yaml
- spec/country_spec.rb
I've used `in_eea?` in the past as a way to determine European Single Market membership, but PR #676 correctly states that Switzerland is not an EEA member, but is a member of the ESM.
This PR adds `#in_esm?` property for counties in the European Single Market, delegating to `in_eea?` if the property is unset.
> Add `#in_esm?` property for countries in the European Single Market

- lib/countries/data/countries/CZ.yaml
Fixes #688 
While there are probably still some inconsistencies, we tend to use the ISO short name instead of the ISO full name for the `name` attribute.
> Update CZ.yaml: Czechia is the ISO short name for the Czech Republic

- lib/countries/data/subdivisions/NO.yaml
As of 2020-11-24, the iso codes have been dramatically updated for Norway, see the bottom of [this page](https://www.iso.org/obp/ui/#iso:code:3166:NO) under "Change history of country code."
The translations were all pulled from https://query.wikidata.org
> Updating Norway subdivision codes to match late 2020 ISO change 

- lib/countries/translations.rb
Fix error when getting ISO3166::Country.translations with a symbol instead of a string when there are custom countries registered.
Fixes #691
> Fix regression in `ISO3166::Country.translations` with symbols

- lib/countries/data/subdivisions/RU.yaml
Ensure that all translations of Moscow Oblast make reference to the fact that it's an "Oblast" or province, so that it is not confused with the city.
I attach the sources:
Netherland: https://no.wikipedia.org/wiki/Moskva_oblast
Thai: https://vi.wikipedia.org/wiki/Moskva_(tỉnh)
> Ensure Moscow Oblast translations reference the "province"

- lib/countries/data/countries/NL.yaml
The Dutch reduced VAT rate was increased from 6% to 9% in 2019: https://www.government.nl/topics/vat/reduced-vat-rate-to-increase-from-6-to-9
Here are todays tariffs: https://www.belastingdienst.nl/wps/wcm/connect/bldcontenten/belastingdienst/business/vat/vat_in_the_netherlands/calculating_vat/vat_tariffs
> Update NL reduced VAT rate

- lib/countries/country/class_methods.rb
- spec/country_spec.rb
- spec/data_spec.rb
The subdivision struct has a `code` parameter, but it's never set because the data doesn't actually contain the subdivision codes (they're used as the keys). 
This is a bit of a pain partly because it was just confusing, but mostly because it means that given a `Subdivision` object it's nearly impossible to actually get the code.
This simply sets the `code` parameter when creating the subdivisions, adds a test and updates other tests as appropriate.
> Set the code when creating subdivisions

- lib/countries/country/class_methods.rb
- spec/country_spec.rb
Fix `ISO3166::Country.respond_to_missing?` for finder methods like `find_country_by_name`
Using rspec-mocks to stub methods on `ISO3166::Country` is broken. As an example, the following snippet raises an error:
```ruby
let(:found_country) { double }
before
allow(ISO3166::Country).to receive(:find_country_by_alpha2)
.and_return(found_country)
end
```
Raises:
```
NoMethodError:
undefined method `all?' for "alpha2":String
```
> Fix ISO3166::Country respond_to_missing?

- lib/countries/data/subdivisions/NZ.yaml
Remove old N and S subdivisions, remove duplicated Chatham Island entry
> Update NZ subdivision data and fix Chatham Island entry

- CHANGELOG.md
Especially for major versions, it's helpful to those who are updating for us to explicitly state which changes are breaking, if any.
> Docs: Changelog for 4.0.0: clarify breaking changes

- lib/countries/data/subdivisions/LV.yaml
Ensure LV subdivisions 111, 112 and 113 have a non-empty translation hash. Fixes #718.
> Fix empty translations in LV subdivisions

- lib/countries/data/subdivisions/US.yaml
- spec/country_spec.rb
Remove US subdivisions AA, AE, AP. 
Armed forces subdivisions are USPS codes, but not ISO subdivisions
> Remove non-ISO US subdivisions

- lib/countries/data/countries/TF.yaml
According to https://en.wikipedia.org/wiki/List_of_countries_by_United_Nations_geoscheme,
French Southern Territories are in the EMEA world region, Africa region and Eastern Africa subregion. As such, the continent should also be Africa. Not ideal, because Adélie Land is in Antartica, but the remaining territories are islands.
> Fix  French Southern Territories continent and region data

- lib/countries/data/countries/IM.yaml
- lib/countries/data/countries/JE.yaml
As per https://en.wikipedia.org/wiki/ISO_4217#Unofficial_currency_codes, IMP and JEP are not official ISO 4217 currencies.
Fixes #492
> JE and IM currencies should be GBP

- lib/countries/data/countries/IL.yaml
- lib/countries/data/countries/SA.yaml
Adds 17 % VAT rate for Israel and 15 % for Saudi Arabia.
Sources:
- https://www.haaretz.com/israel-news/business/.premium-value-added-tax-is-down-as-of-today-but-its-not-out-1.5404351
- https://www.bbc.com/news/business-52612785
> add VAT for Israel and Saudi Arabia

- lib/countries/data/countries/IL.yaml
- lib/countries/data/countries/KH.yaml
- lib/countries/data/countries/TW.yaml
A couple of postal code regexes got recently updated (fetched from `rake postal_codes:update`)
The diff for Israel shows that it's removed, but that's because it was duplicated (line 47-48 in the `IL.yaml` file)
> Update postal code regexes from rake task

- README.markdown
I added the `subdivision_with_names_with_codes` method to the documentation with a small example of the output since I thought it might be useful to know it exists.
> Added subdivision_names_with_codes method in documentation

- lib/countries/data/subdivisions/PT.yaml
Corrected the Portuguese translation of the Portuguese subdivisions.
The "Distrito de" before the district name was inconsistent (only appeared in some of the districts) and is unnecessary and redundant.
> Corrected Portuguese subdivision names

- README.markdown
- lib/countries/country.rb
- lib/countries/country/class_methods.rb
- lib/countries/data.rb
- spec/data_spec.rb
- Move subdivision loading code to `Data` class
- During data load, keep only subdivision translations for the configured locales
- `Data.reset` also resets loaded subdivisions
Fixes #580
> Refactor subdivision loading to respect the configured locales.

- lib/countries/data/countries/VI.yaml
Looking up for an address in Virgin Islands US using Google Maps API responds with U.S. Virgin Islands as the country name:
```json
{
"long_name" : "U.S. Virgin Islands",
"short_name" : "VI",
"types" : [ "country", "political" ]
},
```
This country name isn't specified as an unofficial name so lookup fails:
```ruby
[1] pry(main)> IS
O3166::Country.find_country_by_any_name("U.S. Virgin Islands")
=> nil
```
> Add an alternative name for USVI lookup

- README.markdown
https://github.com/countries/countries/blob/blob/master/UPGRADE.md contains `blob` twice, ending in a wrong URL that returns 404
https://github.com/countries/countries/blob/master/UPGRADE.md works as expected
> Fix Upgrade.md route on README.markdown

- lib/countries/data/translations/countries-de.yaml
These are the regular used names for Cabo Verde and Cote d'Ivoire in Germany.
> german translations for CI and CV

- lib/countries/data/countries/TW.yaml
Unofficial names of Taiwan updated with:
- Traditional Chinese name: '臺灣'
- Simplified Chinese name: '台湾'
> Updated Taiwan unofficial names

- countries.gemspec
- lib/countries.rb
- lib/countries/country/class_methods.rb
This replaces [sixarm_ruby_unaccent](https://github.com/SixArm/sixarm_ruby_unaccent) with [unaccent](https://github.com/hardpixel/unaccent) (Disclaimer: I'm the author of unaccent). Unaccent uses the same accentmap as sixarm_ruby_unaccent so there will be not differences in the final output.
What it does differently is to auto-load the accentmap and use gsub to replace the accented characters. This results in faster conversions and less memory usage as you can see [here](https://github.com/hardpixel/unaccent#benchmark). Also the string extension is optional.
> Replace sixarm_ruby_unaccent with unaccent

- lib/countries/country.rb
- spec/country_spec.rb
> Ensure #translated_names is compacted.

- CHANGELOG.md
The entry mentioning the removal of `i18n_data` was pointing to the incorrect PR.
> Fix changelog to point to correct PR

- README.markdown
It took me some time to figure out how to get an array of country codes. 
So I'd rather make it visible. 
My use case: I want to validate a country code user input against `ISO3166::Country.codes`.
Country codes are also called alpha2 in the documentation. This made it harder to find that the `ISO3166::Country.codes` method actually returns alpha2.
> Document how to get country codes (alpha2) [ci skip]

- lib/countries/configuration.rb
Duplicate `I18n.available_locales` into `default_locales` to prevent accidental changes to the original array
Fixes #768
> Duplicate `I18n.available_locales` into `default_locales`

- lib/countries/country.rb
- spec/country_spec.rb
Add Country#subdivision_names method - returns a list of subdivision names for a country.
This makes it possible to search for countries based on a subdivision name, eg: `ISO3166::Country.find_by_subdivision_names(...)` or `ISO3166::Country.find_all_by(:subdivision_names, ...)`
Addresses #786
> Add Country#subdivision_names method 

- lib/countries/country.rb
- lib/countries/data/countries/AR.yaml
- lib/countries/data/countries/AU.yaml
- lib/countries/data/countries/BR.yaml
- lib/countries/data/countries/CA.yaml
- lib/countries/data/countries/CN.yaml
- lib/countries/data/countries/DE.yaml
- lib/countries/data/countries/FR.yaml
- lib/countries/data/countries/GB.yaml
- lib/countries/data/countries/ID.yaml
- lib/countries/data/countries/IN.yaml
- lib/countries/data/countries/IT.yaml
- lib/countries/data/countries/JP.yaml
- lib/countries/data/countries/KR.yaml
- lib/countries/data/countries/MX.yaml
- lib/countries/data/countries/RU.yaml
- lib/countries/data/countries/SA.yaml
- lib/countries/data/countries/TR.yaml
- lib/countries/data/countries/US.yaml
- lib/countries/data/countries/ZA.yaml
Added G20 and G7 member fields.
- G7 members: Canada, France, Germany, Italy, Japan, the United Kingdom and the United States
- G20 members: Argentina, Australia, Brazil, Canada, China, France, Germany, India, Indonesia, Italy, Japan, Mexico, Russia, Saudi Arabia, South Africa, South Korea, Turkey, the U.K. and the U.S.
Two methods, in_g7? and in_g20?, were added to check if a country is a member.
> Added G20 and G7 member fields

- README.md
- lib/countries/country.rb
- spec/country_spec.rb
* If a country is part of the European Economic Area, they must adhere to the regulations set forth in the General Data Protection Regulation (GDPR). This decision was made through Decision No. 154/2018, which extended the reach of the EU's GDPR law to all EEA jurisdictions that weren't members of the EU.
* Even though the UK has left the EU as of January 2021, the GDPR was already in effect and remains a valid UK law.
* To ensure that the UK is included as a GDPR-compliant country, this Pull Request is necessary as the current `eea` flag does not provide this information.
> Adding gdpr_compliant method to check if a country is regulated by GDPR

- lib/countries/data/countries/TW.yaml
> Fix Taiwan's iso_long_name not matching ISO data.

- lib/countries/data/translations/countries-pt_BR.yaml
We prefer the wording Azerbaijão to refer to Azerbaijan
This can be verified by:
1. Searching through pt-br google which corrects us to use `Azerbaijão` instead of `Azerbaidjão`
2. The Brazilian Central Bank also uses `Azerbaijão` word:
https://www.bcb.gov.br/ftp/paises.txt code: `00736` or https://www.bcb.gov.br/acessoinformacao/legado?url=https:%2F%2Fwww.bcb.gov.br%2Frex%2FCenso2000%2Fport%2Fmanual%2Fpais.asp%3Fidpai%3Dcenso2000inf 
3. Or, my preferred, on Brazil F1 🏎️  we call it Grand Prix of `Azerbaijão` 😄
> Fix Azerbaijão wording in pt-BR

- lib/countries/data/subdivisions/US.yaml
In the file `lib/countries/data/subdivisions/US.yaml` under "GA/translations" the key "tk" is duplicated. This can cause problems with libraries that do strict checks like [`go-yaml.v3`](https://github.com/go-yaml/yaml).
This PR removes the duplicate key.
> Remove duplicate key in subdivisions/US.yaml

- lib/countries/country.rb
- lib/countries/country/class_methods.rb
- lib/countries/country/country_subdivision_methods.rb
- lib/countries/country/emoji.rb
- lib/countries/country/finder_methods.rb
At work, we've been using this gem at scale (serving ~ 20-100M req/month), and detected this gem to pollute memory by allocating way too many strings.
We've been running this adjustment of freezing multiple strings for six months now without issues (and measurably lower memory footprint).
Sadly, I couldn't find our exact memory profiling results anymore (we did extensive before/after tests using the memory profiler gem and observing memory footprint on the servers).
I remember, that strings for country codes got allocated multiple times before, and only once after freeze strings.
Thank you for maintaining open source :-)
> Freeze Strings

- Gemfile
- Gemfile.lock
Minor cleanup; it seems this gem is not used anywhere.
Bundle install did a minor bump of nokogiri, that should be OK I guess.
> remove unused gem retryable

- lib/countries/data/subdivisions/IN.yaml
Changes of subdivision codes from India: 
1. CT => 'CG' 
2. OR => 'OD' 
3. TG => 'TS' 
4. UT => 'UK'
https://en.wikipedia.org/wiki/ISO_3166-2:IN
https://www.iso.org/obp/ui/#iso:code:3166:IN
> Updates for India subdivision codes

- lib/countries/data/countries/CZ.yaml
This PR contains updates to languages and VAT rates for Czechia.
The only official language in Czechia is Czech. Slovak is also no longer considered a spoken language as it's only spoken by the Slovak minority nowadays.
https://european-union.europa.eu/principles-countries-history/country-profiles/czechia_en
As of 1 January 2024, the reduced VAT rate was changed to 12%.
https://www.globalvatcompliance.com/vat-rates-in-czech-republic/
> Update language and reduced VAT rate for Czechia

- lib/countries/data/countries/BG.yaml
Adds the unofficial localized name of Bulgaria in Bulgarian (Cyrillic): `България`.
> Adds the unofficial localized name of Bulgaria in Bulgarian

- lib/countries/data/subdivisions/GT.yaml
https://www.iso.org/obp/ui/#iso:code:3166:GT
> 2021-11-25 | Change of subdivision code from GT-AV to GT-16, GT-BV to GT-15, GT-CM to GT-04, GT-CQ to GT-20, GT-ES to GT-05, GT-GU to GT-01, GT-HU to GT-13, GT-IZ to GT-18, GT-JA to GT-21, GT-JU to GT-22, GT-PE to GT-17, GT-PR to GT-02, GT-QC to GT-14, GT-QZ to GT-09, GT-RE to GT-11, GT-SA to GT-03, GT-SM to GT-12, GT-SO to GT-07, GT-SR to GT-06, GT-SU to GT-10, GT-TO to GT-08, GT-ZA to GT-19; Update Code Source
> Update GT subdivisions

- lib/countries/data/countries/CH.yaml
Switzerland changed their VAT rates by beginning of 2024.
Reference:
https://www.estv.admin.ch/estv/en/home/value-added-tax/vat-rates-switzerland.html
> Change VAT rates for CH valid from 2024-01-01

- lib/countries/data/countries/GB.yaml
Hi,
Currently, using the `find_country_by_any_name` method does not return the record for "Great Britain" because the alternative that exists in unofficial names has an extra part, meaning that to be found you have to search using `ISO3166::Country.find_country_by_any_name(" Great Britain (UK)")`, but in my understanding it should also be returned in the simple name format, which would be `ISO3166::Country.find_country_by_any_name("Great Britain")`.
> Add Great Britain as an Unofficial Name for GB

- lib/countries/data/countries/CD.yaml
- lib/countries/data/countries/CG.yaml
Added unofficial names for Congo (Kinshasa) and Congo (Brazzaville).
Added "Congo (Kinshasa)" as an unofficial name for Democratic Republic of the Congo (ISO 3166-1 alpha-2 code: CD).
Added "Congo (Brazzaville)" as an unofficial name for Republic of the Congo (ISO 3166-1 alpha-2 code: CG).
These names are also utilized by OpenFlights (https://openflights.org/data.php) to enhance compatibility and ease of integration with existing datasets and applications.
> Update CD.yaml and CG.yaml

- lib/countries/data/countries/FI.yaml
Finland changed their general VAT rate to 25.5 as of 2024-09-01.
Source: https://www.vero.fi/en/businesses-and-corporations/taxes-and-charges/vat/rates-of-vat/
> VAT rate for Finland changed to 25.5% as of 2024-09-01

- lib/countries/configuration.rb
- spec/configuration_spec.rb
While analyzing my project's load times, I realized that the country initializer took almost a second:
```
start = Time.now;
ISO3166.configure do |config|
config.locales = %i[en fr]
end
puts "Time elapsed #{(Time.now - start) * 1000} ms"
```
I was able to break it down to this line:
https://github.com/countries/countries/blob/master/lib/countries/configuration.rb#L25
In my project, `I18n.available_locales` is being set later during the initialization.
Because of that, the default `I18n.available_locales` are being loaded, which take some time to initialize.
While in most projects `I18n.available_locales` should be set earlier,
just lazily loading the default locales might be a good improvement anyway.
```
without lazy default locales: Time elapsed 965.10 ms
with lazy default locales: Time …
```
> Lazy load default locales

- lib/countries/data/subdivisions/NP.yaml
This PR updates the federal subdivisions of Nepal to include the new provinces (Koshi, Madhesh, Bagmati, Gandaki, Lumbini, Karnali and Sudurpashchim) as per the new federal structure. It also retains the previous development regions and zones for historical purposes.
- Added 7 new provinces with their official names as `type: province`.
- Updated YAML structure with geo-coordinates, translations, and codes for provinces.
> Update Federal Subdivisions of Nepal with New Provinces

- countries.gemspec
I noticed that the project already has a FUNDING.yml. This PR adds the `funding_uri` to your gemspec to help increase visibility using the `bundle fund` command in Bundler.
> Add funding_uri to gemspec

- lib/countries/data/countries/DO.yaml
Source: https://www.countrycodeguide.com/north-america/dominican-republic
> Add nanp_prefix to DO

- lib/countries/data/countries/VA.yaml
Source: https://www.countrycodeguide.com/europe/vatican
> Add nanp_prefix to VA

- lib/countries/data/countries/VI.yaml
Source: https://www.countrycodeguide.com/north-america/us-virgin-islands-
> Add nanp_prefix to VI

- lib/countries/data/countries/MP.yaml
Source: https://www.countrycodeguide.com/oceania/northern-mariana-islands
> Add nanp_prefix to MP

- lib/countries/data/countries/CW.yaml
- lib/countries/data/countries/SX.yaml
The ANG currency was withdrawn as of 2025-03 in Curacao and Saint Maarten.
> fix: currency of Curacao and Saint Maarten

- lib/countries/data/translations/countries-pt_BR.yaml
Official Singapore website: https://www.mfa.gov.sg/Overseas-Mission/Brasilia/BP/Brasilia-BP/Mission-Updates/2015/12/Emb_new_port_29122015
**pt-BR**
> A grafia do nome do nosso país finalmente será unificada. Até agora, todos os dicionários aceitavam as duas grafias. No entanto, o Acordo Ortográfico de 1990 (que entrou em vigor apenas em 2009 e será obrigatório a partir de 1º de janeiro de 2016) determina a adoção da grafia "Singapura", pondo fim a uma dúvida comum entre os brasileiros. Então, a partir de 1º de janeiro de 2016, somente uma forma será correta: "Singapura"!
**en**
> The spelling of our country's name will finally be standardized. Until now, all dictionaries accepted both spellings. However, the Orthographic Agreement of 1990 (which only came into effect in 2009 and will be …
> Fix SG - Singapore country name in pt-BR

- lib/countries/data/subdivisions/ZA.yaml
The official name of the province is `North West`, not `North-West`.
Source: https://www.gov.za/provinces
> Correct ZA province name

- lib/countries/data/subdivisions/FR.yaml
- lib/countries/data/translations/countries-fr.yaml
In file `lib/countries/data/subdivisions/FR.yaml` : 
- use French name `Nouvelle-Calédonie` for `New Caledonia` as subdivision of France country
In file `lib/countries/data/translations/countries-fr.yaml` : 
- add `CP: Clipperton` because there is also `TF: Terres australes françaises` in the same file
> fix: change french name of France subdivisions

- lib/countries/country/finder_methods.rb
- spec/country_spec.rb
Hi,
After the release of Country version 8, certain parts of our application began breaking with the following error:
```
NoMethodError:
undefined method `[]' for nil
```
We traced the issue to the `matches` variable being `nil` and still being accessed with an index in `finder_methods`. To reproduce this, I’ve added a spec that demonstrates the failure.
This PR fixes the issue by adding a guard clause to return early, if `matches` is `nil` preventing the `NoMethodError`.
<hr>
The behavior surfaced when using the gem in combination with the CanCanCan authorization gem. Internally, CanCanCan calls `respond_to?(:arr)` on the `ISO3166::Country` object. That call triggered the error shown above.
If this fix isn’t appropriate or there's a preferred way of doing it, kindly comment :)
> fix: add guard clause to check if matches is nil
