lib/data/countries.yaml, lib/data/subdivisions/JP.yaml
This was done programmatically, so I broke out the Yaml reparse into a single commit to make the changes more readable.
=> Adding Address format for New Caledonia, Thailand and Liechtenstein

lib/data/countries.yaml
see e.g. http://en.wikipedia.org/wiki/Saint_Barth%C3%A9lemy#Economy
=> Saint Barthélemy uses the Euro

lib/data/countries.yaml
Added another names for countries
- Côte D'Ivoire
- United Kingdom
- Croatia
- Iran
- Saint Kitts And Nevis
- North Korea
- Libya
and others.
=> Add more names for some countries

lib/data/countries.yaml
=> Corrected NZ national_prefix

lib/data/countries.yaml
also fixed the English translation for Andorra
=> Arabic Translations and names

lib/data/countries/AS.yaml, lib/data/countries/CW.yaml, lib/data/countries/GU.yaml, lib/data/countries/PR.yaml, lib/data/countries/VI.yaml
added bounding box coordinates for VI, CW, PR, AS, and GU
Source: http://isithackday.com/geoplanet-explorer
=> Add missing countries bounding box

lib/data/subdivisions/IN.yaml
A new state formed in India after bifurcation of AP state. So added it.
=> Added newly formed state(Telangana), after bifurcation of AP in India

lib/countries/version.rb
As I currently have to use the master version of this gem to fix the issue solved by #256
=> Bump version

lib/data/subdivisions/NA.yaml
I've updated the latest Namibia subdivisions based upon http://en.wikipedia.org/wiki/ISO_3166-2:NA
There are some others that I can start updating to make sure this list is the latest and greatest but I wanted to get your feedback on this change before doing so.
Thanks!
=> Update NA subdivisions to latest ISO3166

lib/data/countries/BR.yaml
=> Add `pt-BR` as primary language for Brazil

lib/countries/country.rb, spec/country_spec.rb
=> Adding compare operation to country

lib/data/countries/NO.yaml
=> Correct NL to NO for un_locode.

lib/data/subdivisions/DK.yaml
=> Fix spelling of Sjælland

lib/data/countries/BO.yaml
=> Boliva does not use zip codes

lib/countries/data/countries/NO.yaml
Norway seems to be missing its GEC code, so I have added it.
=> Add GEC code for Norway

Rakefile
the dir structure seems to have changed.
also, loading countries instead of i18n_data produced some strange warnings.
=> fix cache updater

lib/countries/data/subdivisions/ES.yaml
I've used the official data from http://www.ine.es/en/daco/daco42/codmun/cod_provincia_en.htm
I've also completed all the `names` lists to include the name used in `name` and the individual names from official names that look like `Araba/Álava`.
I kept the alternative names that were already listed.
=> Official Spain's subdivision names

lib/countries/data.rb, spec/configuration_spec.rb, spec/data_spec.rb
@rposborne 
Fix and test for #346 . 👍
=> fix Data#load_cache from throwing exception when missing locale file

lib/countries/data/countries/CH.yaml
I added the vat rates for CH.
I didn't understand what super_reduced is used for.
=> add vat rates for CH

lib/countries/data/subdivisions/UY.yaml
Hi! We would love to have this included, if possible. Thanks!
=> Add Canelones to Uruguay's subdivisions

README.markdown
As mentioned in [issue 378](https://github.com/hexorx/countries/issues/378)
=> Add Documentation for Country Code Emoji Flags

README.markdown, spec/country_spec.rb, spec/global_spec.rb, spec/timezone_spec.rb
noticed some typos while going through the gem
thanks for making the gem - I use it regularly
=> Fix typos in specs and readme

lib/countries/data/countries/TF.yaml
add missing phone country code for French Southern Territories
=> added country code for French Southern Territories

lib/countries/data/countries/AG.yaml, lib/countries/data/countries/AI.yaml, lib/countries/data/countries/AS.yaml, lib/countries/data/countries/BB.yaml, lib/countries/data/countries/BM.yaml, lib/countries/data/countries/BS.yaml, lib/countries/data/countries/DM.yaml, lib/countries/data/countries/GD.yaml, lib/countries/data/countries/GU.yaml, lib/countries/data/countries/JM.yaml, lib/countries/data/countries/KN.yaml, lib/countries/data/countries/KY.yaml, lib/countries/data/countries/LC.yaml, lib/countries/data/countries/MS.yaml, lib/countries/data/countries/SX.yaml, lib/countries/data/countries/TC.yaml, lib/countries/data/countries/TT.yaml, lib/countries/data/countries/VC.yaml, lib/countries/data/countries/VG.yaml
=> added NPN code after country code NANP

lib/countries/data/countries/BO.yaml, lib/countries/data/countries/CD.yaml, lib/countries/data/countries/CI.yaml, lib/countries/data/countries/CV.yaml, lib/countries/data/countries/CZ.yaml, lib/countries/data/countries/FM.yaml, lib/countries/data/countries/GB.yaml, lib/countries/data/countries/HM.yaml, lib/countries/data/countries/IR.yaml, lib/countries/data/countries/KN.yaml, lib/countries/data/countries/KP.yaml, lib/countries/data/countries/KR.yaml, lib/countries/data/countries/MD.yaml, lib/countries/data/countries/MF.yaml, lib/countries/data/countries/MK.yaml, lib/countries/data/countries/PM.yaml, lib/countries/data/countries/SH.yaml, lib/countries/data/countries/SJ.yaml, lib/countries/data/countries/SX.yaml, lib/countries/data/countries/TW.yaml, lib/countries/data/countries/VA.yaml, lib/countries/data/countries/VC.yaml, lib/countries/data/countries/VE.yaml, lib/countries/data/countries/VG.yaml, lib/countries/data/countries/VI.yaml, lib/countries/data/countries/VN.yaml
As discussed here: https://github.com/hexorx/countries/issues/413
=> Update all official country names to the ISO 3166 standard

lib/countries/data/countries/AX.yaml, lib/countries/data/countries/BL.yaml, lib/countries/data/countries/BV.yaml, lib/countries/data/countries/GG.yaml, lib/countries/data/countries/IM.yaml, lib/countries/data/countries/JE.yaml, lib/countries/data/countries/MF.yaml, lib/countries/data/countries/PS.yaml, lib/countries/data/countries/TF.yaml, lib/countries/data/countries/TL.yaml
source: http://www.unece.org/cefact/locode/subdivisions.html
related to #418
=> Add missing un location codes

lib/countries/data/countries/GF.yaml
Source: https://en.wikipedia.org/wiki/French_Guiana
=> Adds French Guiana nationality

lib/countries/data/countries/SA.yaml
Add `Kingdom of Saudi Arabia` to unofficial names.
=> Add Kingdom of Saudi Arabia

lib/countries/data/countries/NP.yaml
Added more ISO 639-2 code of languages spoken in Nepal:
Here is the issue link: https://github.com/hexorx/countries/issues/440
=> More languages spoken in Nepal

lib/countries/data/subdivisions/FR.yaml
Hi @rposborne,
France has new Metropolitan regions since January 1st, 2016.
[https://en.wikipedia.org/wiki/ISO_3166-2:FR](url)
Thanks for this great gem!
=> Add new French Regions (January 2016)

lib/countries/data/countries/NO.yaml
=> Add standard vat rate for Norway

lib/countries/data/countries/BY.yaml
https://en.wikipedia.org/wiki/Belarusian_ruble
> In July 2016, a new ruble was introduced (ISO 4217 code BYN), at a rate of 1 BYN = 10,000 BYR.
=> Update BY currency code (BYR -> BYN)

lib/countries/data/translation_corrections.yaml
=> Swedish translation correction of GB

lib/countries/data/countries/CZ.yaml
CZ country name needs to be updated to Czech Republic
=> Update CZ country name

lib/countries/data/subdivisions/CU.yaml, lib/countries/data/subdivisions/EC.yaml, lib/countries/data/subdivisions/MX.yaml, lib/countries/data/subdivisions/PA.yaml, lib/countries/data/subdivisions/PE.yaml, lib/countries/data/subdivisions/PR.yaml
Some Latin America countries had old info about their subdivisions.
=> Update and fix LatAm countries subdivisions

lib/countries/data/countries/MR.yaml
=> Update Mauritanian currency code

lib/countries/data/countries/SZ.yaml
=> Update name of SZ to eSwatini (was Swaziland)

lib/countries/data/countries/WS.yaml
=> Samoa currency is WST

lib/countries/data/countries/GB.yaml
For when the day actually comes 😢
=> 🇬🇧🇪🇺 Britain leaves the EU and EEA

lib/countries/data/subdivisions/ES.yaml
This PR:
- Adds some unofficial names
- Adds some missing translations
- Removes a bunch of ² that where in there
- Ensures unofficial names is always a list, even if there's only one item
=> [ES] Add unofficial names + translations + remove weird characters

lib/countries/data/countries/TV.yaml
See https://github.com/RubyMoney/money/issues/932
=> Use AUD currency for Tuvalu

lib/countries/data/countries/CL.yaml
http://www.sii.cl/destacados/foreign_investor/vat.html
=> added CL standard VAT

lib/countries/data/countries/HM.yaml
Refer to https://www.iso.org/obp/ui/#search
'Heard Island and McDonald Islands' get a country code of 334
**UPDATE**: actually, the country code is 672.
=> Add country code 672 to HM

.github/workflows/tests.yml, .travis.yml, countries.gemspec, lib/countries.rb, lib/countries/country/class_methods.rb
Add Github actions on top of PR #650
=> Add Github actions on top of PR #650

lib/countries/data/translation_corrections.yaml
I'm assuming this is the intended page.
=> translation_corrections.yaml: Fix broken link

lib/countries/data/translation_corrections.yaml
To fix this issue https://github.com/hexorx/countries/issues/659
=> Correct Danish translation of CZ

.github/workflows/tests.yml, .travis.yml
=> Update CI to the latests ruby point versions

countries.gemspec, lib/countries/data/translation_corrections.yaml
- Update I18nData gem to 0.13.1
- add manual correction of MK in `mk` locale
=> Update I18nData gem to 0.13.1 and fix MK translation in `mk` locale

lib/countries/country/class_methods.rb, spec/country_spec.rb
=> add Country.pluck

lib/countries/data/subdivisions/CZ.yaml, lib/countries/data/subdivisions/FI.yaml, lib/countries/data/subdivisions/GR.yaml, lib/countries/data/subdivisions/PL.yaml
Superseeds #600 by @donnen
Fix merge conflicts and update CZ, GR, FI and PL subdivision data to match current ISO data
=> Update subdivisions, fix #600 conflicts

lib/countries/data/translation_corrections.yaml
Bad data from i18n_data gem, already fixed upstream but unreleased.
=> Update translation corrections for Occitan.

countries.gemspec
=> Update i18n_data to 0.15.0

lib/countries/data/subdivisions/MK.yaml
Update 2020-03-02 - https://www.iso.org/obp/ui/#iso:code:3166:MK
Fixes #674
=> Update MK subdivisions 

lib/countries/data/subdivisions/KE.yaml
=> Update Kenya subdivision data

lib/countries/data/subdivisions/SG.yaml
=> Fix SG subdivision data

lib/countries/data/subdivisions/CZ.yaml
Fixes #732;
Add missing names to CZ subdivisions
=> Fix duplicated translations of CZ-10 subdivision

CHANGELOG.md, README.markdown, countries.gemspec
http:// -> https://.
Plus, fix links.
=> http:// -> https://

README.markdown
As per https://github.com/rubygems/rubygems/pull/5337, we can simplify the steps of adding a gem.
=> Use bundle add instead

lib/countries/data/translation_corrections.yaml
=> Fix common name for IR

lib/countries/data/subdivisions/MX.yaml
=> Update MX subdivisions: Remove DIF and update some unofficial names

lib/countries/data/translations/countries-fr.yaml
All first letter must be uppercase.
=> Update french, missing uppercase letters

lib/countries/data/countries/TR.yaml, lib/countries/data/translations/countries-ab.yaml, lib/countries/data/translations/countries-ak.yaml, lib/countries/data/translations/countries-an.yaml, lib/countries/data/translations/countries-ay.yaml, lib/countries/data/translations/countries-ba.yaml, lib/countries/data/translations/countries-bi.yaml, lib/countries/data/translations/countries-ch.yaml, lib/countries/data/translations/countries-ee.yaml, lib/countries/data/translations/countries-en.yaml, lib/countries/data/translations/countries-gn.yaml, lib/countries/data/translations/countries-ki.yaml, lib/countries/data/translations/countries-kl.yaml, lib/countries/data/translations/countries-sd.yaml, lib/countries/data/translations/countries-sw.yaml, lib/countries/data/translations/countries-tl.yaml, lib/countries/data/translations/countries-ve.yaml, lib/countries/data/translations/countries-xh.yaml, spec/country_spec.rb
The name change is official. I also created a MR for `i18n_data` 
https://github.com/grosser/i18n_data/pull/62
=> Rename turkey to Türkiye

CHANGELOG.md, lib/countries/data/countries/HR.yaml
=> Update Croatia's currency to EUR

lib/countries/data/countries/GF.yaml, lib/countries/data/countries/GP.yaml, lib/countries/data/countries/MF.yaml, lib/countries/data/countries/MQ.yaml, lib/countries/data/countries/RE.yaml, lib/countries/data/countries/YT.yaml
Source https://fr.wikipedia.org/wiki/R%C3%A9gion_ultrap%C3%A9riph%C3%A9rique
It seems there is no English page about this on Wikipedia :/
=> fix: RUP are part of the European Union

lib/countries/data/translations/countries-gn.yaml
=> Fix wrong translation of MY in gn locale

lib/countries/country.rb, spec/country_spec.rb
=> Wrap postal code format regex in anchors

lib/countries/data/subdivisions/IR.yaml
=> Fix wrong subdivision code for IR-09

lib/countries/data/countries/LB.yaml
Lebanon IOC code is LBN since 2016.
=> Update LB.yaml IOC code

lib/countries/data/countries/AM.yaml, lib/countries/data/countries/AR.yaml, lib/countries/data/countries/CH.yaml, lib/countries/data/countries/ES.yaml, lib/countries/data/countries/FJ.yaml, lib/countries/data/countries/UZ.yaml
Add the languages to ES (https://en.wikipedia.org/wiki/Languages_of_Spain#Present-day_languages)
Fixes #852
Also updates official languages in a few countries that had outdated entries
=> Languages updates

lib/countries/data/countries/ER.yaml
=> Fix ER currency code

lib/countries/country/finder_methods.rb, spec/country_spec.rb
Fixes https://github.com/countries/countries/issues/863
=> fix and tests

lib/countries/data/countries/UM.yaml
=> Add nanp_prefix to UM

lib/countries/data/countries/SK.yaml
See https://trade.ec.europa.eu/access-to-markets/en/news/recent-vat-changes-certain-eu-member-states
=> Update SK VAT rates for 2025

lib/countries/country/country_subdivision_methods.rb, lib/countries/subdivision.rb, spec/country_spec.rb, spec/subdivision_spec.rb
Fix https://github.com/countries/countries/issues/888
=> Find correct subdivision when searching for Washington

lib/countries/country.rb, spec/country_spec.rb
=> Add #pluck support
